### ISSUE TITLE
render-site file not found

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/platypub#2]
Sorry if this is jumping the gun while you're in progress: getting error not finding `./render-site` when doing a Preview:

```
[clojure-agent-send-off-pool-4] INFO com.platypub - Generating CSS...
[clojure-agent-send-off-pool-4] INFO com.platypub - CSS done
[qtp169775100-19] ERROR com.biffweb.impl.middleware - Exception while handling request
clojure.lang.ExceptionInfo: chmod: cannot access './render-site': No such file or directory
 {:exit 1, :out "", :err "chmod: cannot access './render-site': No such file or directory\n"}
        at com.biffweb.impl.util$sh.invokeStatic(util.clj:66)
        at com.biffweb.impl.util$sh.doInvoke(util.clj:62)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at com.biffweb$sh.invokeStatic(biffweb.clj:61)
        at com.biffweb$sh.doInvoke(biffweb.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at com.platypub.feat.sites$generate_BANG_.invokeStatic(sites.clj:121)
        at com.platypub.feat.sites$generate_BANG_.invoke(sites.clj:107)
        at com.platypub.feat.sites$preview.invokeStatic(sites.clj:128)
        at com.platypub.feat.sites$preview.invoke(sites.clj:125)
```

https://github.com/jacobobryant/platypub/blob/fda203e6351e6523148fb070913ce871bf050453/src/com/platypub/feat/sites.clj#L121

**Comment by jacobobryant** [comment]
yeah, things are a bit of a mess right now... however I went ahead and cleaned some stuff up, including updating all the default theme code (which I just finished writing for https://blog.thesample.ai anyway), so things should work now. after pulling the new code, you'll need to re-copy `themes.TEMPLATE/default` to `themes/default`, and I've also included some more details in `README.md` and `themes/default/README.md`. Also see `config.edn.TEMPLATE` for a comment about setting some recaptcha config which is new.

I just did a test speedrun with a fresh clone and everything seems to be working. The site's deployed at https://sparkling-sprinkles-125cac.netlify.app/ in fact. Let me know if you run into any pitfalls. The user experience could definitely use more work.
